### ISSUE TITLE
HTTPSConnectionPool error when creating pull zones via api

### ISSUE THREAD

**Issue by adamdbradley** [MaxCDN/rws-bugs#2] opened 2012-12-06 15:17 UTC
Receiving this error message when trying to create a pull zone with the new api:

HTTPSConnectionPool(host='rws.netdna.com', port=443): Max retries exceeded with url.

I'm calling the API from Google App Engine (python), and I'm wondering if it has to do with this:

Installing NetDNA Python Client
Before you can properly install the NetDNA Python client program, some packages need to be present in your system. Make sure that requests and certifi packages are already installed. Requests is an HTTP library written in Python while he certifi package is an SSL library.

Any clues how to get around this on google app engine? Also, I'm able to use the old API just fine, and I'm also able to purge the cache and get pull zone information without any errors.

**Comment by dlitvakb** [comment] 2012-12-06 17:15
There is currently a problem with RWS when enforcing SSLv2 or SSLv3 rejecting the current certificates, we are solving this.

Meanwhile, can you work with HTTP instead of HTTPS?

For doing that you can use the following:

``` python
from netdnarws import NetDNA

api = NetDNA('alias', 'secret', 'key', secure_connection=False)
```

**Comment by adamdbradley** [comment] 2012-12-06 17:49
I can set it to HTTP for the time being, but I prefer not to send my secret key in plain text. Will this be resolved in the near future, or not going to be solved for another few months?

Also, why does it work fine when I GET pull zone information? Is it because the create pull zone is a POST?

**Comment by dlitvakb** [comment] 2012-12-06 18:21
It should be fixed soon, we are already working on it, setting up a new box for the service.

It should be failing the same both in GET and POST requests, currently the problem is that we have various certificates installed in the box and the one for RWS cant resolve a unique IP, that is getting fixed soon.

**Comment by eamonnscu** [comment] 2012-12-07 02:11
Hey Adam,

The issue mentioned by David L was resolved today around 3PM PST. Though I believe this is not the cause of your issue, can you please give it another try now and let me know?

**Comment by jdorfman** [comment] 2013-02-19 19:50
@adamdbradley has this been resolved?  Closing for now, please re-open if needed.

**Closed as completed by jdorfman** 2013-02-19 19:50 UTC
Labels: bug
